config/routes.rb
Overnights::Application.routes.draw do
  
  resources :visualizations

  root :to => "tasks#index"

  resources :date_ranges

  resources :tasks

  match '/refresh_badges', to: 'application#refresh_badges', via: :get
  match 'uploads/refresh_table', to: 'uploads#refresh_table', via: :get 
  resources :uploads

	
  get "static_pages/home"
  get "static_pages/help"
  resources :demos

  resources :markets

  resources :channels

  resources :programs

  resources :program_slots

  

end
=begin

=end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Task < ActiveRecord::Base

	has_many :uploads
end

app/controllers/tasks_controller.rb
require "rake"

#Rake::Task.clear
#overnights::Application.load_tasks

class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    #@tasks = Task.all
	#Render all tasks except ones that are reserved for administrator such as channels parsing
	@tasks = Task.where.not(id: 1)
	
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
      <tr>
		<td> <%= task.name %></td>
		<td> <%= task.description %></td>
		<td><%=render "uploads/form" , :task => task %></td>
      </tr>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div >
<%= button_to_function "Show/Hide Instructions", "$('.instructions').toggle()" %></h5>
</div>
<div class="instructions">
<pre>
<b>Step 1:  Uploading files to the server to be parsed:</b>
<ol>
<li>Convert BBM Excel files to csv using Open Office on a Mac</li>
<li>Filenames should should be EXACTLY the same as Name columns below(including Capital letter). eg: National.csv, Toronto.csv, Calgary.csv...</li>
<li>Choose a File then Upload it</li>
<li>Once all files are uploaded proceed to Step 2: Uploads</li>
</ol>
</pre>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
	  <th>Description</th>
	  <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |t| %>
      <tr>
		<td> <%= t.name %></td>
		<td> <%= t.description %></td>
<% if false%>
The following method will render the form partial from the uploads view 
and call the create method from the uploads. Pass the upload object to the create
method. which will reroute to upload/index with a flash notification
<% end %>
		<td><%=render "uploads/form" , :task => t %></td>
	
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>