config/routes.rb
Overnights::Application.routes.draw do
  
  resources :visualizations

  root :to => "tasks#index"

  resources :date_ranges

  resources :tasks

  match '/refresh_badges', to: 'application#refresh_badges', via: :get
  match 'uploads/refresh_table', to: 'uploads#refresh_table', via: :get 
  resources :uploads

	
  get "static_pages/home"
  get "static_pages/help"
  resources :demos

  resources :markets

  resources :channels

  resources :programs

  resources :program_slots

  

end
=begin

=end

app/models/visualization.rb
# == Schema Information
#
# Table name: visualizations
#
#  id          :integer          not null, primary key
#  created_at  :datetime
#  updated_at  :datetime
#  name        :string(255)
#  description :string(255)
#  code        :string(255)
#

class Visualization < ActiveRecord::Base
end

app/controllers/visualizations_controller.rb
class VisualizationsController < ApplicationController
  before_action :set_visualization, only: [:show, :edit, :update, :destroy]

  # GET /visualizations
  def index
    @visualizations = Visualization.all
  end

  # GET /visualizations/1
  def show

  end

  # GET /visualizations/new
  def new
    @visualization = Visualization.new
  end

  # GET /visualizations/1/edit
  def edit
  end

  # POST /visualizations
  def create
    @visualization = Visualization.new(visualization_params)

    if @visualization.save
      redirect_to @visualization, notice: 'Visualization was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /visualizations/1
  def update
    if @visualization.update(visualization_params)
      redirect_to @visualization, notice: 'Visualization was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /visualizations/1
  def destroy
    @visualization.destroy
    redirect_to visualizations_url, notice: 'Visualization was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visualization
      @visualization = Visualization.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def visualization_params
      params.require(:visualization).permit(:name, :description, :code)
    end
end

app/helpers/visualizations_helper.rb
module VisualizationsHelper
end

app/views/visualizations/_form.html.erb
<%= simple_form_for @visualization, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :code %>
  <%= f.input :description %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                visualizations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/visualizations/edit.html.erb
<%- model_class = Visualization -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/visualizations/index.html.erb
<h1>Listing visualizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th> Code</th>
      <th>Description</th>
      <th>  </th>
    </tr>
  </thead>

  <tbody>
    <% @visualizations.each do |visualization| %>
      <tr>
		<td><%=visualization.name%></td>
		<td><%=visualization.code%> </td>
		<td><%=visualization.description%></td>
<td>   </td>
		<td><%= link_to 'Edit', edit_visualization_path(visualization) %></td>
		<td><%= link_to 'Show', visualization %></td>
		<td><%= link_to "Delete", visualization, :confirm => "Delete Visualization?", :method => :delete %></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visualization', new_visualization_path %>

app/views/visualizations/new.html.erb
<h1>New visualization</h1>

<%= render 'form' %>

<%= link_to 'Back', visualizations_path %>

app/views/visualizations/show.html.erb
<%= javascript_include_tag "visualization_show" %>
<header>
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th> Code</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
      <tr>
		<td><%=@visualization.name%></td>
		<td><%=@visualization.code%> </td>
		<td><%=@visualization.description%></td>
      </tr>

  </tbody>
</table>

</header>

<body>
<div id="bar_graph">

</body>




<p>
<%= link_to 'Edit', edit_visualization_path(@visualization) %> |
<%= link_to 'Back', visualizations_path %>
</p>