config/routes.rb
Overnights::Application.routes.draw do
  
  resources :visualizations

  root :to => "tasks#index"

  resources :date_ranges

  resources :tasks

  match '/refresh_badges', to: 'application#refresh_badges', via: :get
  match 'uploads/refresh_table', to: 'uploads#refresh_table', via: :get 
  resources :uploads

	
  get "static_pages/home"
  get "static_pages/help"
  resources :demos

  resources :markets

  resources :channels

  resources :programs

  resources :program_slots

  

end
=begin

=end

app/models/upload.rb
# == Schema Information
#
# Table name: uploads
#
#  id                      :integer          not null, primary key
#  created_at              :datetime
#  updated_at              :datetime
#  sourcedata_file_name    :string(255)
#  sourcedata_content_type :string(255)
#  sourcedata_file_size    :integer
#  sourcedata_updated_at   :datetime
#  task_id                 :integer
#  status                  :integer          default(0), not null
#  f_path                  :string(255)
#  job                     :string(255)
#  daterange               :string(255)
#  email                   :string(255)
#  total_rows              :integer
#  rows_completed          :integer
#

#

# upload status can have values : 
# -1 = File deleted
#  0 = error
#  1 = File saved on server - show button
#  2 = entered in DB - hide button
#  3 = entering in DB - hide button
#  4 = add button clicked - hide button

# task_id: 
# 1=>mode=channel, market=nil, 
# 2=>mode=national, market=National, 
# 3=>mode=regional, market=Toronto, 
# 4=>mode=regional, market=Calgary, 
# 5=>mode=regional, market=Edmonton, 
# 6=>mode=regional, market=Vancouver, 

class Upload < ActiveRecord::Base
	belongs_to :task
	#has_and_belongs_to_many :date_ranges, :uniq => true
	#After deprecation warning in Rails 4 changed the above to the following:
	has_and_belongs_to_many :date_ranges, -> { uniq }
	validates_presence_of :sourcedata	
	validate :fileName
	

	has_attached_file(
					:sourcedata,
					:path => "#{Rails.root}/imports/#{Date.today.to_s}/#{Time.now.strftime("%H_%M" )}/:basename.:extension",
					)
	
	def fileName
		if(sourcedata_file_name.blank?)
			errors.add(:sourcedata_file_name, "cannot be blank")
		else
			s = sourcedata_file_name.split(".")[0]
			if s != task.name
				errors.add(:sourcedata_file_name, "-- ERROR -- file name doesn't match the market" )
			end
		end
	end

	def add_data_to_DB()
		puts "entered upload model/add_data_to_DB method"
		mode = nil
	
		market = nil
		case self.task_id
			when 1
				mode = :channel
				market = nil
			when 2
				mode = :national
				market = :national
			when 3
				mode = :regional
				market = :toronto
			when 4
				mode = :regional
				market = :calgary
			when 5
				mode = :regional
				market = :edmonton
			when 6
				mode = :regional
				market = :vancouver
			else
				puts"Error!! Received invalid task.id to parse"
			end
	options = Hash[:file_path => self.f_path , :mode =>mode, :market=>market, :upload_id =>self.id]
	puts "Calling CSV parser with \noptions= #{options.inspect}"
	#self.update!(:status => 3)
	@cp = CsvParser.new(options)
	end
	handle_asynchronously :add_data_to_DB
	
	def percentage_complete
		return 0 if total_rows.nil? || total_rows == 0
		((rows_completed + 1).to_f / total_rows.to_f ) * 100
	end


end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [ :edit, :update, :destroy] #This call back is applied to onky these actions

  # GET /uploads
  def index
    @uploads = Upload.all
	update_file_status
	@uploads = Upload.all
  end

  # GET /uploads/1
  def show
  end

  # GET /uploads/new
  def new
	puts "Running uploads/new"
    @upload = Upload.new()
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
=begin
The following method will render the form partial from the uploads view 
and call the create method from the uploads. Pass the upload object to the create
method. which will reroute to upload/index with a flash notification
=end
  def create
	
	@upload = Upload.new(upload_params)
	if @upload.save
		@upload.update!(:status => "1")
		@upload.update!(:f_path => "#{@upload.sourcedata.path}")
		redirect_to uploads_url, notice: "Upload for #{@upload.task.name} was successfully created with file #{@upload.sourcedata_file_name}."
    else
      	redirect_to tasks_url, alert: "*** ERROR *** Upload for #{@upload.task.name} did not go through successfully. #{@upload.errors.messages}"
    end
  end

  # PATCH/PUT /uploads/1
  	def update
		puts "Update method in Uploads controller received params = #{params.inspect}"
		puts "params[:upload][:job] = #{params[:upload][:job].inspect}"
		#When Button "Add to DB is pressed the following code is evoked"
		if (params[:upload][:job] == "parse")
			puts "Passed params[:job]== \"parse\" "
			
			redirect_to uploads_url, notice: "Parsing data from #{@upload.sourcedata_file_name}....."
			@upload.delay.add_data_to_DB()
			@upload.update!(:status => 4)
		else
			if @upload.update(upload_params)
				redirect_to uploads_url, notice: "#{@upload.sourcedata_file_name} was updated"
    		else
				redirect_to uploads_url, notice: "ERRRO #{@upload.sourcedata_file_name} could NOT be updated"
    		end
		end
	end


  # DELETE /uploads/1
  def destroy
    @upload.destroy
    redirect_to uploads_url, notice: 'Couldnt parse file #{@upload.sourcedata_file_name}'
  end
	
	# GET /uploads/refresh_table
	def refresh_table
		@uploads = Upload.all
		update_file_status
		@uploads = Upload.all
		respond_to do |format|
			format.js # template marked refresh_table.js.erb will be evoked
			#format.html {redirect_to uploads_url}			
		end
	end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:upload][:id])
    end

    # Only allow a trusted parameter "white list" through.
    def upload_params
		#removed the line below as it was causing an exception when the upload button was pressed
		params.require(:upload).permit(:sourcedata, :task_id, :status, :f_path, :job)
		#params.permit(:id, :sourcedata, :task_id, :status, :f_path)
    end

	def update_file_status
	@uploads.each do |u|
		if(File.exist?(u.f_path))
			puts "File #{u.sourcedata_file_name} exists"
		else
			puts "File #{u.sourcedata_file_name} has been removed"
			u.update!(:status => "-1")
		end
	end
	end

end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_button.html.erb
<%#When this button is pressed UploadsController#update is fired with parameter "job= parse"%>
<%= simple_form_for upload do |f| %>
<%= f.hidden_field :id, :value => upload.id %>
<%= f.hidden_field :job, :value => "parse"%>
	<%if (upload.status == 0)%>
		<%= "Error" %>
	<%elsif (upload.status == 1)%>
		<%= f.button :submit, "Add \n#{upload.sourcedata_file_name}\n to Database", :class=> "add_data_button" %>
	<%elsif (upload.status == 2)%>
		<%= "File has been added to DB" %>
	<%elsif (upload.status == 3)%>
		<%= "File is being added to DB" %>
	<%else %>
		<%= "File has been removed from server" %>
	<%end%>
<% end %>

app/views/uploads/_form.html.erb
<%= simple_form_for task.uploads.build, :html=> {:multipart => true} do |f| %>
    <%= f.hidden_field :task_id, :value => task.id %>

 	<%= f.error_notification %>
	<%= f.file_field :sourcedata %>
	<%= f.button :submit, "Upload this file \nto server" ,:confirm => "Upload File",:class=> "upload_tasks_button"%>
 
<% end %>

app/views/uploads/_show_upload.html.erb
<tr id= "show_upload_table_rows">
		
		<td> <%="#{@u.sourcedata_file_name}"%></td>
			 <% path_arr = @u.f_path.split("\/")%>
		<td><%= path_arr[-3..-2].join(", ").gsub!("_", "\:")%></td>
		<td> <%= @u.sourcedata_content_type%></td>
		<td> <%= @u.date_ranges.pluck(:date_range).join(", ")%>
		<td> <%= @u.total_rows%></td>
		<td> <%= @u.rows_completed%></td>
		<%if (@u.status == 0 ) %>
			<td id="red_row">Error </td>
		<%elsif (@u.status == 1 ) %>
			<td id="yellow_row">File saved on server to be parsed</td>
		<%elsif (@u.status == 3 ) %>
			<td id="yellow_row">File is being parsed </td>	
		<%elsif (@u.status == 2 ) %>
			<td id="green_row">File parsing Complete </td>	
		<%else%>
			<td id="red_row">File doesn't exist on Server</td>	
		<%end%>

</tr>

app/views/uploads/_upload.html.erb
<tr id= "uploads_table_rows">
		<%if (upload.status == 0 ) %>
			<%if (["1","2","3","4"].include?"#{upload.status}") %>
				<td class="red_row"> <%= button_to "View File: #{upload.sourcedata_file_name}", upload,  :method=>:get%></td>
			<%else%>
				<td class="red_row"> <%= "#{upload.sourcedata_file_name}"%></td>
			<%end%>
			 <% path_arr = upload.f_path.split("\/")%>
		<td class="red_row"><%= path_arr[-3..-2].join(", ").gsub!("_", "\:")%></td>
		<td class="red_row"> <%= upload.sourcedata_content_type%></td>
		<td class="red_row"> <%= upload.date_ranges.pluck(:date_range).join(", ")%>
		<td class="red_row"> <%= upload.total_rows%></td>
		<td class="red_row"> <%= upload.rows_completed%></td>
        <td class="red_row"> <%= number_to_percentage(upload.percentage_complete, :precision => 0)%></td>
		</td>			
			<td class="red_row">Error- Contact Ash </td>
			<td class="red_row"></td>	
		<%elsif (upload.status == 1 ) %>
<%if (["1","2","3","4"].include?"#{upload.status}") %>
				<td class="grey_row"> <%= button_to "View File: #{upload.sourcedata_file_name}", upload,  :method=>:get%></td>
			<%else%>
				<td class="grey_row"> <%= "#{upload.sourcedata_file_name}"%></td>
			<%end%>
			 <% path_arr = upload.f_path.split("\/")%>
		<td class="grey_row"><%= path_arr[-3..-2].join(", ").gsub!("_", "\:")%></td>
		<td class="grey_row"> <%= upload.sourcedata_content_type%></td>
		<td class="grey_row"> <%= upload.date_ranges.pluck(:date_range).join(", ")%>
		<td class="grey_row"> <%= upload.total_rows%></td>
		<td class="grey_row"> <%= upload.rows_completed%></td>
        <td class="grey_row"> <%= number_to_percentage(upload.percentage_complete, :precision => 0)%></td>
		</td>				
<td class="grey_row">File saved-Click button to start parsing</td>
			<td class="grey_row"><%= render 'button', :upload => upload%></td>
		<%elsif (upload.status == 3 ) %>
<%if (["1","2","3","4"].include?"#{upload.status}") %>
				<td class="red_row"> <%= button_to "View File: #{upload.sourcedata_file_name}", upload,  :method=>:get%></td>
			<%else%>
				<td class="red_row"> <%= "#{upload.sourcedata_file_name}"%></td>
			<%end%>
			 <% path_arr = upload.f_path.split("\/")%>
		<td class="red_row"><%= path_arr[-3..-2].join(", ").gsub!("_", "\:")%></td>
		<td class="red_row"> <%= upload.sourcedata_content_type%></td>
		<td class="red_row"> <%= upload.date_ranges.pluck(:date_range).join(", ")%>
		<td class="red_row"> <%= upload.total_rows%></td>
		<td class="red_row"> <%= upload.rows_completed%></td>
        <td class="red_row"> <%= number_to_percentage(upload.percentage_complete, :precision => 0)%></td>
		</td>				
			<td class="red_row">Parsing in progress.......</td>	
			<td class="red_row"></td>	
		<%elsif (upload.status == 2 ) %>

<%if (["1","2","3","4"].include?"#{upload.status}") %>
				<td class="green_row"> <%= button_to "View File: #{upload.sourcedata_file_name}", upload,  :method=>:get%></td>
			<%else%>
				<td class="green_row"> <%= "#{upload.sourcedata_file_name}"%></td>
			<%end%>
			 <% path_arr = upload.f_path.split("\/")%>
		<td class="green_row"><%= path_arr[-3..-2].join(", ").gsub!("_", "\:")%></td>
		<td class="green_row"> <%= upload.sourcedata_content_type%></td>
		<td class="green_row"> <%= upload.date_ranges.pluck(:date_range).join(", ")%>
		<td class="green_row"> <%= upload.total_rows%></td>
		<td class="green_row"> <%= upload.rows_completed%></td>
        <td class="green_row"> <%= number_to_percentage(upload.percentage_complete, :precision => 0)%></td>
		</td>		
			<td class="green_row">Parsing Complete! </td>	
				<td class="green_row"></td>	
		<%elsif (upload.status == 4 ) %>

<%if (["1","2","3","4"].include?"#{upload.status}") %>
				<td class="yellow_row"> <%= button_to "View File: #{upload.sourcedata_file_name}", upload,  :method=>:get%></td>
			<%else%>
				<td class="yellow_row"> <%= "#{upload.sourcedata_file_name}"%></td>
			<%end%>
			 <% path_arr = upload.f_path.split("\/")%>
		<td class="yellow_row"><%= path_arr[-3..-2].join(", ").gsub!("_", "\:")%></td>
		<td class="yellow_row"> <%= upload.sourcedata_content_type%></td>
		<td class="yellow_row"> <%= upload.date_ranges.pluck(:date_range).join(", ")%>
		<td class="yellow_row"> <%= upload.total_rows%></td>
		<td class="yellow_row"> <%= upload.rows_completed%></td>
        <td class="yellow_row"> <%= number_to_percentage(upload.percentage_complete, :precision => 0)%></td>
		</td>		



			<td class="yellow_row">Waiting for previous file to complete ... in queue</td>	
			<td class="yellow_row"></td>	
		<%else%>

<%if (["1","2","3","4"].include?"#{upload.status}") %>
				<td class="grey_row"> <%= button_to "View File: #{upload.sourcedata_file_name}", upload,  :method=>:get%></td>
			<%else%>
				<td class="grey_row"> <%= "View File: #{upload.sourcedata_file_name}"%></td>
			<%end%>
			 <% path_arr = upload.f_path.split("\/")%>
		<td class="grey_row"><%= path_arr[-3..-2].join(", ").gsub!("_", "\:")%></td>
		<td class="grey_row"> <%= upload.sourcedata_content_type%></td>
		<td class="grey_row"> <%= upload.date_ranges.pluck(:date_range).join(", ")%>
		<td class="grey_row"> <%= upload.total_rows%></td>
		<td class="grey_row"> <%= upload.rows_completed%></td>
        <td class="grey_row"> <%= number_to_percentage(upload.percentage_complete, :precision => 0)%></td>
		</td>		



			<td class="grey_row">File doesn't exist on Server</td>	
			<td class="grey_row"></td>	
		<%end%>


</tr>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<div>
<%= button_to_function "Show/Hide Instructions", "$('.instructions').toggle()" %>
</div>
<div class="instructions">
<pre >
<b>Step 2: Adding data from files to the Database</b>
<ol>
<li>Verify all file names are in the right naming convention eg: National.csv, Calgary.csv, etc...</li>
<li>If no, re upload the correct files</li>
<li>Note that you can see the time of the file uploaded and the date in the columns for sanity check</li>
<li>Before you start the import, the <b>total rows</b> is empty</li>
<li>You will know that the imports have begun when you press the <b>Import button</b> and <b>Refesh the webpage</b></li>
<li>Notice after starting a file import and refreshing the page the total rows shows a number and percentage completed is populated</li>
<li>Keep periodically refreshing the page to get updated counts</li>
<li>You can hit the import button on all the files to be imported. They will run simultaneously in order to speed up the process</li>
</ol>
</pre>
</div>
<div id="uploads_table">
<table class="table table-striped">
  <thead>
    <tr>
	  
	  <th>File name</th>
	  <th>Upload Date,Time</th>
	  <th>File Type</th>
	  <th>Calendar Air Dates in file</th>
	  <th>Total Rows</th>
	  <th>Rows read</th>
	  <th>Completed</th>
	  <th>Status</th>
	  <th>Actions</th>
    </tr>
  </thead>
  <tbody id="table_rows">
    <%= render (@uploads)%> <%# partial _upload.html.erb %> 
  </tbody>

</div>
</table>

<%= content_for :bottom_javascripts do %>
<%= javascript_tag do %> 
alert("Testing")
<%end%>
<%end%>

app/views/uploads/index.js.erb
$('#').hide()

app/views/uploads/new.html.erb
Upload CSV file for <%= @upload.market%>

<%= render 'form' %>

app/views/uploads/refresh_table.js.erb
$('#table_rows').html("<%=escape_javascript(render(@uploads)) %>");
$('.yellow_row').css({'background-color':'#FFCC33'});
$('.red_row').css({'background-color':'#FFFFFF'}).animate({'background-color':'#E80000  '}, 2000);
$('.green_row').css({'background-color':'#66CC99'});
$('.grey_row').css({'background-color':'#C8C8C8'});

app/views/uploads/show.html.erb
<%= button_to 'Back to Uploads Page', uploads_path, :method=>:get %>


<%@u = Upload.find(params[:id]) %>
<div  id="upload_show">
<table class="table table-striped">
  <thead>
    <tr> 
	  <th>File name</th>
	  <th>Upload Date,Time</th>
	  <th>File Type</th>
	  <th>Program Dates in file</th>
	  <th>Total Rows</th>
	  <th>Rows read</th>
	  <th>Status</th>
    </tr>
  </thead>
  <tbody id="show_table_rows">
    <%= render :partial=> "show_upload", :object=>@u %> 
  </tbody>
</div>


<%= p = "#{Rails.root}" + "#{@u.f_path.split('imports')[1]}"%>
<pre >
<%=render :file => "#{@u.f_path}"%>
</pre>