config/routes.rb
Overnights::Application.routes.draw do
  
  resources :visualizations

  root :to => "tasks#index"

  resources :date_ranges

  resources :tasks

  match '/refresh_badges', to: 'application#refresh_badges', via: :get
  match 'uploads/refresh_table', to: 'uploads#refresh_table', via: :get 
  resources :uploads

	
  get "static_pages/home"
  get "static_pages/help"
  resources :demos

  resources :markets

  resources :channels

  resources :programs

  resources :program_slots

  

end
=begin

=end

app/views/layouts/_badge_values.html.erb
 <ul class="nav nav-pills nav-stacked">
				<li class="label label-info"><span class="badge pull-right"></span><%= link_to "Tasks", tasks_url %></li>
				<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"><%= @badge_values[:uploads_count]%></span><%= link_to "Uploads", uploads_url %></li>
<li>" "</li>
              	<li class="label label-info"><span class="badge pull-right"><%=@badge_values[:channel_count]%></span><%= link_to "Channels", channels_url  %></li>
<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"><%=@badge_values[:program_count]%></span><%= link_to "Programs", programs_url  %></li>
<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"></span><%= link_to "Markets", markets_url  %></li>
<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"><%=@badge_values[:demo_count] / 3%></span><%= link_to "Demos", demos_url %></li>
<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"><%=@badge_values[:program_slot_count]%></span><%= link_to "ProgramSlots", program_slots_url  %></li>
<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"></span><%= link_to "Visualization", visualizations_url  %></li>

            </ul>

app/views/layouts/_blank_badges.html.erb
 <ul class="nav nav-pills nav-stacked">
				<li class="label label-info"><span class="badge pull-right"></span><%= link_to "Tasks", tasks_url %></li>
				<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"></span><%= link_to "Uploads", uploads_url %></li>
<li>" "</li>
              	<li class="label label-info"><span class="badge pull-right"></span><%= link_to "Channels", channels_url  %></li>
<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"></span><%= link_to "Programs", programs_url  %></li>
<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"></span><%= link_to "Markets", markets_url  %></li>
<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"></span><%= link_to "Demos", demos_url %></li>
<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"></span><%= link_to "ProgramSlots", program_slots_url  %></li>
<li>" "</li>
				<li class="label label-info"><span class="badge pull-right"></span><%= link_to "Visualization", visualizations_url  %></li>
            </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : " App" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  

<body data-no-turbolink>
<nav class="navbar navbar-inverse" role="navigation">
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%=tasks_url %>">App</a>
          <div id="refresh_badge" class="container-fluid nav-collapse">
			<% if @badge_values.blank? %>
			<%= render "layouts/blank_badges" %>
			<%else%> 
			<%= render @badge_values %>
			<%end%>
          </div><!--/.nav-collapse -->

        </div>
      </div>
    </div>
</nav>
<pre>
<font color="blue"><b>Feedback about this app?<u><a href="mailto:xxxx@example.com">
</a></u></br>
Bugs/errors? Log them Here <a href="https://docs.google.com/document/kjkkk=sharing"><b><u>Link to maintenance Log</u></b></a></font>

</pre>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/refresh_badges.js.erb
$('#refresh_badge').html("<%= escape_javascript render 'layouts/badge_values'%>");